from app.schemas import EligibilitySummary, PharmacyInfo


def parse_mock_271(raw_271: str) -> EligibilitySummary:
    """
    Parses the simplified mock 271 string generated by edi_generator.py
    back into a structured JSON-friendly response.
    """
    segments = [seg for seg in raw_271.split("~") if seg.strip()]

    coverage_status = "manual_review"
    copay_amount = None
    pharmacy = PharmacyInfo()
    notes: list[str] = []

    for seg in segments:
        parts = seg.split("*")
        tag = parts[0]

        if tag == "EB" and len(parts) >= 3:
            status = parts[2].lower()
            if status in {"active", "inactive", "manual_review"}:
                coverage_status = status

        elif tag == "COPAY" and len(parts) >= 2:
            try:
                copay_amount = int(parts[1])
            except ValueError:
                notes.append("Invalid copay value in 271 response.")

        elif tag == "RX" and len(parts) >= 3:
            rx_type = parts[1]
            rx_value = parts[2]

            if rx_type == "BIN":
                pharmacy.bin = rx_value
            elif rx_type == "PCN":
                pharmacy.pcn = rx_value
            elif rx_type == "GRP":
                pharmacy.group = rx_value

        elif tag == "MSG" and len(parts) >= 2:
            notes.append(parts[1])

    pharmacy_output = None
    if pharmacy.bin or pharmacy.pcn or pharmacy.group:
        pharmacy_output = pharmacy

    return EligibilitySummary(
        coverage_status=coverage_status,  # type: ignore[arg-type]
        copay_amount=copay_amount,
        pharmacy=pharmacy_output,
        notes=notes,
    )